from flask import Blueprint, render_template, request, session, redirect, url_for, flash, send_file, abort
from routes.auth import login_required
from models.profile import ProfileModel
from models.report import ReportModel
from models.token import TokenModel
from models.access_log import AccessLogModel
from services.storage import LocalStorageService
from database.db import get_db

emergency_bp = Blueprint('emergency', __name__, url_prefix='/emergency')

@emergency_bp.route('/')
@login_required
def index():
    """Emergency share overview hub for the authenticated patient."""
    user_id = session.get('user_id')
    db = get_db()

    profile = ProfileModel.get_by_user_id(user_id)
    reports = ReportModel.get_by_user_id(user_id)
    
    # Check count of AI summaries available
    summaries = db.execute("""
        SELECT s.*, r.original_filename, r.file_type 
        FROM ai_summaries s
        JOIN medical_reports r ON s.report_id = r.id
        WHERE r.user_id = ?
        ORDER BY s.created_at DESC
    """, (user_id,)).fetchall()

    # Active and historical emergency tokens generated by the patient
    tokens = TokenModel.get_by_user_id(user_id)

    # Recent emergency access audit logs
    access_logs = AccessLogModel.get_by_user_id(user_id, limit=25)

    return render_template(
        'emergency/index.html',
        profile=profile,
        reports=reports,
        summaries=summaries,
        tokens=tokens,
        access_logs=access_logs
    )

@emergency_bp.route('/view')
@login_required
def emergency_view():
    """
    Consolidated Emergency Medical Profile (authenticated preview).
    Allows the patient to review what an emergency doctor will see.
    """
    user_id = session.get('user_id')
    db = get_db()

    profile = ProfileModel.get_by_user_id(user_id)
    reports = ReportModel.get_by_user_id(user_id)
    
    summaries = db.execute("""
        SELECT s.*, r.original_filename, r.file_type, r.id as report_id
        FROM ai_summaries s
        JOIN medical_reports r ON s.report_id = r.id
        WHERE r.user_id = ?
        ORDER BY s.created_at DESC
    """, (user_id,)).fetchall()

    return render_template(
        'emergency/view.html',
        profile=profile,
        reports=reports,
        summaries=summaries
    )

@emergency_bp.route('/tokens/create', methods=['POST'])
@login_required
def create_token():
    """Generate a new temporary emergency access token with an expiration time."""
    user_id = session.get('user_id')
    label = request.form.get('label', '').strip() or "Emergency Link"
    try:
        duration_hours = float(request.form.get('duration_hours', 24))
        if duration_hours <= 0 or duration_hours > 720:  # Up to 30 days max
            duration_hours = 24
    except ValueError:
        duration_hours = 24

    raw_token, token_record = TokenModel.create(user_id=user_id, duration_hours=duration_hours, label=label)
    if raw_token and token_record:
        access_url = url_for('emergency.public_access', token_str=raw_token, _external=True)
        session['active_emergency_url'] = access_url
        session['active_emergency_token'] = raw_token
        flash(f"Emergency access link created! Valid for {int(duration_hours)} hour(s). URL: {access_url}", "success")
    else:
        flash("Failed to generate emergency token. Please try again.", "danger")

    return redirect(url_for('emergency.index'))

@emergency_bp.route('/tokens/<int:token_id>/revoke', methods=['POST'])
@login_required
def revoke_token(token_id):
    """Revoke an active emergency token immediately."""
    user_id = session.get('user_id')
    success = TokenModel.revoke(token_id=token_id, user_id=user_id)
    if success:
        session.pop('active_emergency_url', None)
        session.pop('active_emergency_token', None)
        flash("Emergency access link revoked immediately. Any further attempts to use it will be blocked.", "info")
    else:
        flash("Could not revoke token or token not found.", "warning")

    return redirect(url_for('emergency.index'))

@emergency_bp.route('/<token_str>')
@emergency_bp.route('/access/<token_str>')
def public_access(token_str):
    """
    Public Emergency Medical Profile Viewer.
    Accessible without an account to emergency physicians / paramedics using a valid token.
    Strictly isolated from patient account sessions.
    """
    ip_address = request.remote_addr
    user_agent = request.headers.get('User-Agent', '')

    token, status = TokenModel.validate_token(token_str)

    # 1. Invalid token (non-existent)
    if status == 'INVALID':
        return render_template(
            'emergency/access_error.html',
            error_title="Invalid Emergency Link",
            error_message="The emergency access token provided does not exist or has an incorrect format.",
            status="INVALID"
        ), 404

    # Log token identifier (masked for security)
    if 'token_prefix' in token.keys() and token['token_prefix']:
        token_ident = f"emg_{token['token_prefix']}..."
    elif 'token' in token.keys() and token['token']:
        token_ident = f"emg_{token['token'][:6]}...{token['token'][-4:]}"
    else:
        token_ident = f"emg_{token_str[:6]}..."
    patient_id = token['user_id']

    # 2. Revoked token
    if status == 'REVOKED':
        AccessLogModel.log(
            user_id=patient_id,
            action='VIEW_PROFILE',
            status='REVOKED',
            token_id=token['id'],
            token_identifier=token_ident,
            ip_address=ip_address,
            user_agent=user_agent
        )
        return render_template(
            'emergency/access_error.html',
            error_title="Access Denied: Link Revoked",
            error_message="This emergency link was revoked by the patient and is no longer valid.",
            status="REVOKED"
        ), 403

    # 3. Expired token
    if status == 'EXPIRED':
        AccessLogModel.log(
            user_id=patient_id,
            action='VIEW_PROFILE',
            status='EXPIRED',
            token_id=token['id'],
            token_identifier=token_ident,
            ip_address=ip_address,
            user_agent=user_agent
        )
        return render_template(
            'emergency/access_error.html',
            error_title="Access Denied: Link Expired",
            error_message=f"This emergency link expired on {token['expires_at']}.",
            status="EXPIRED"
        ), 403

    # 4. Valid token -> Log success and render clinical profile
    AccessLogModel.log(
        user_id=patient_id,
        action='VIEW_PROFILE',
        status='SUCCESS',
        token_id=token['id'],
        token_identifier=token_ident,
        ip_address=ip_address,
        user_agent=user_agent
    )

    db = get_db()
    profile = ProfileModel.get_by_user_id(patient_id)
    # Only show medical reports that patient has explicitly permitted
    reports = ReportModel.get_emergency_reports(patient_id)
    allowed_report_ids = [r['id'] for r in reports]

    # Only show AI summaries for permitted reports
    summaries = []
    if allowed_report_ids:
        placeholders = ','.join(['?'] * len(allowed_report_ids))
        summaries = db.execute(f"""
            SELECT s.*, r.original_filename, r.file_type, r.id as report_id
            FROM ai_summaries s
            JOIN medical_reports r ON s.report_id = r.id
            WHERE r.id IN ({placeholders})
            ORDER BY s.created_at DESC
        """, allowed_report_ids).fetchall()

    return render_template(
        'emergency/public_view.html',
        profile=profile,
        reports=reports,
        summaries=summaries,
        token=token,
        raw_token=token_str
    )

@emergency_bp.route('/<token_str>/report/<int:report_id>')
@emergency_bp.route('/access/<token_str>/report/<int:report_id>')
def public_download_report(token_str, report_id):
    """
    Stream a medical report to an emergency responder using a valid token.
    Validates token validity, verifies report belongs to patient,
    and enforces emergency_access_allowed permission.
    """
    ip_address = request.remote_addr
    user_agent = request.headers.get('User-Agent', '')

    token, status = TokenModel.validate_token(token_str)
    if status != 'VALID':
        abort(403, description="Access token is invalid, expired, or revoked.")

    patient_id = token['user_id']
    token_ident = f"emg_{token['token_prefix']}..." if 'token_prefix' in token.keys() and token['token_prefix'] else "emg_token"

    report = ReportModel.get_user_report(report_id, patient_id)
    if not report:
        abort(404, description="Report not found or not associated with this emergency profile.")

    # Check emergency access permission
    if 'emergency_access_allowed' in report.keys() and report['emergency_access_allowed'] == 0:
        AccessLogModel.log(
            user_id=patient_id,
            action='DOWNLOAD_REPORT_BLOCKED',
            status='BLOCKED_PERMISSION',
            token_id=token['id'],
            token_identifier=token_ident,
            ip_address=ip_address,
            user_agent=user_agent,
            report_id=report_id
        )
        abort(403, description="Access denied: Patient has marked this report private from emergency access.")

    # Log successful report access
    AccessLogModel.log(
        user_id=patient_id,
        action='DOWNLOAD_REPORT',
        status='SUCCESS',
        token_id=token['id'],
        token_identifier=token_ident,
        ip_address=ip_address,
        user_agent=user_agent,
        report_id=report_id
    )

    try:
        abs_path = LocalStorageService.get_absolute_path(report['file_path'])
        if not abs_path.exists():
            abort(404, description="Physical file not found in storage.")

        mimetype = 'application/pdf' if report['file_type'] == 'PDF' else 'text/plain'
        return send_file(
            str(abs_path),
            as_attachment=False,
            mimetype=mimetype,
            download_name=report['original_filename']
        )
    except Exception:
        abort(500, description="Error reading document.")
