import secrets
from datetime import datetime, timedelta
from database.db import get_db

class TokenModel:
    """Helper functions for temporary emergency access token generation and validation."""

    @staticmethod
    def create(user_id, duration_hours=2, label="Emergency Link"):
        """
        Generate a cryptographically secure, unguessable emergency token with an expiration time.
        """
        db = get_db()
        token = secrets.token_urlsafe(24)
        
        # Calculate expiration timestamp in UTC/standard ISO format
        expires_at = (datetime.now() + timedelta(hours=float(duration_hours))).strftime('%Y-%m-%d %H:%M:%S')

        cursor = db.execute("""
            INSERT INTO emergency_tokens (user_id, token, label, expires_at)
            VALUES (?, ?, ?, ?)
        """, (user_id, token, label.strip() or "Emergency Link", expires_at))
        db.commit()

        return TokenModel.get_by_id(cursor.lastrowid)

    @staticmethod
    def get_by_id(token_id):
        """Fetch token by ID."""
        db = get_db()
        return db.execute(
            "SELECT * FROM emergency_tokens WHERE id = ?",
            (token_id,)
        ).fetchone()

    @staticmethod
    def get_by_token(token_str):
        """Fetch token by token string."""
        db = get_db()
        return db.execute(
            "SELECT * FROM emergency_tokens WHERE token = ?",
            (token_str.strip(),)
        ).fetchone()

    @staticmethod
    def validate_token(token_str):
        """
        Validates token status.
        Returns (token_row, status_code) where status_code is one of:
        'VALID', 'EXPIRED', 'REVOKED', 'INVALID'
        """
        token = TokenModel.get_by_token(token_str)
        if not token:
            return None, "INVALID"

        if token['is_revoked']:
            return token, "REVOKED"

        # Check expiration
        try:
            expires_at = datetime.strptime(token['expires_at'], '%Y-%m-%d %H:%M:%S')
            if datetime.now() > expires_at:
                return token, "EXPIRED"
        except Exception:
            pass

        return token, "VALID"

    @staticmethod
    def get_by_user_id(user_id):
        """Fetch all emergency tokens generated by a patient."""
        db = get_db()
        rows = db.execute("""
            SELECT * FROM emergency_tokens
            WHERE user_id = ?
            ORDER BY created_at DESC
        """, (user_id,)).fetchall()

        # Augment with live status indicator for easy template rendering
        token_list = []
        now = datetime.now()
        for r in rows:
            token_dict = dict(r)
            try:
                exp = datetime.strptime(token_dict['expires_at'], '%Y-%m-%d %H:%M:%S')
                token_dict['is_expired'] = (now > exp)
            except Exception:
                token_dict['is_expired'] = False
            token_list.append(token_dict)

        return token_list

    @staticmethod
    def revoke(token_id, user_id):
        """
        Revoke an active emergency token.
        Ensures users can only revoke their own tokens.
        """
        db = get_db()
        cursor = db.execute("""
            UPDATE emergency_tokens
            SET is_revoked = 1
            WHERE id = ? AND user_id = ?
        """, (token_id, user_id))
        db.commit()
        return cursor.rowcount > 0
